


sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

url: voiceingov.org
name: Vox Populi
description: >
  “Ministers… cannot in any country be
  uninfluenced by the voice of the
  people.”


